# Generated by Django 2.0.1 on 2018-01-22 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_date', models.DateField()),
                ('ssn', models.CharField(error_messages={'unique': 'Check SSN. It probably already exists'}, max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{9}$')])),
            ],
            options={
                'db_table': 'people',
                'managed': True,
            },
        ),
    ]
