# Generated by Django 2.0.1 on 2018-02-13 04:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vin_number', models.CharField(blank=True, error_messages={'unique': 'VIN already exists'}, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9A-Z]{17}$')])),
                ('make', models.CharField(blank=True, max_length=15, null=True)),
                ('model', models.CharField(blank=True, max_length=15, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('vehicle_type', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'vehicles',
                'managed': True,
            },
        ),
    ]
